from com.android.monkeyrunner import MonkeyRunner,MonkeyDevice
from com.android.monkeyrunner.easy import EasyMonkeyDevice
from com.android.monkeyrunner.easy import By
import os

print os.system('ifconfig')

easy_device = MonkeyRunner.waitForConnection()     
#easy_device = EasyMonkeyDevice(device)
easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(80,380,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(10.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(3.0)
easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(80,380,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(7.0)
easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(240,380,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(10.0)
easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(80,440,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(7.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)

easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(240,380,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(7.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(80,440,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(7.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)

easy_device.press('KEYCODE_MENU',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(1.0)
easy_device.touch(80,440,MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(7.0)

easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)
easy_device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
MonkeyRunner.sleep(2.0)




